### ISSUE TITLE
Option noEmit doesn't work

### ISSUE THREAD

**Issue by hhyyrylainen** [baptistedonaux/brunch-typescript#26]
I was getting this error while trying to build typescript files: `error: Compiling of app/drawable.ts failed. Debug Failure. False expression: Output generation failed`

Looks like if I put `"noEmit": true,` in my tsconfig.json, to prevent my error checker from generating any files, brunch-typescript fails to override that. 
Even if I put this in my brunch-config.coffee:
```
plugins:
    brunchTypescript:
        noEmit: false
        removeComments: true
        watch: false
```

I found a dirty hack to fix this: put this line in transpile.js (after `options.noResolve = true;` line):
`options.noEmit = false;`
